--DROP TABLE aux.FINANCIAMENTO_TESTE

SELECT *
FROM aux.FINANCIAMENTO_TESTE

-------------------------

UPDATE aux.FINANCIAMENTO_TESTE SET
VL_FINANCIAMENTO = REPLACE(VL_FINANCIAMENTO,'.','')


ALTER TABLE aux.FINANCIAMENTO_TESTE ALTER COLUMN VL_FINANCIAMENTO BIGINT

ALTER TABLE aux.FINANCIAMENTO_TESTE ALTER COLUMN ANO INT

DELETE FROM aux.FINANCIAMENTO_TESTE
WHERE ANO IN (0,2012)

ALTER TABLE aux.FINANCIAMENTO_TESTE ALTER COLUMN CD_EMPRESA INT

ALTER TABLE aux.FINANCIAMENTO_TESTE ALTER COLUMN CD_INDICE INT

UPDATE aux.FINANCIAMENTO_TESTE SET
CD_INDICE = NULL
WHERE CD_INDICE = 0


UPDATE aux.FINANCIAMENTO_TESTE SET
TX_MULTIPLICADOR_INDICE = REPLACE(TX_MULTIPLICADOR_INDICE,',','.')

UPDATE aux.FINANCIAMENTO_TESTE SET
TX_MULTIPLICADOR_INDICE = NULL
WHERE TX_MULTIPLICADOR_INDICE = ' '

ALTER TABLE aux.FINANCIAMENTO_TESTE ALTER COLUMN TX_MULTIPLICADOR_INDICE DECIMAL(20,10)

UPDATE F SET
TX_MULTIPLICADOR_INDICE = 100
FROM aux.FINANCIAMENTO_TESTE F
WHERE CD_INDICE > 0
AND TX_MULTIPLICADOR_INDICE IS NULL

UPDATE aux.FINANCIAMENTO_TESTE SET
TX_ADICIONAL = REPLACE(TX_ADICIONAL,',','.')

UPDATE aux.FINANCIAMENTO_TESTE SET
TX_ADICIONAL = NULL
WHERE TX_ADICIONAL = ' '

ALTER TABLE aux.FINANCIAMENTO_TESTE ALTER COLUMN TX_ADICIONAL DECIMAL(20,10)


ALTER TABLE aux.FINANCIAMENTO_TESTE ALTER COLUMN CD_INDICE_2 INT

UPDATE aux.FINANCIAMENTO_TESTE SET
CD_INDICE_2 = NULL
WHERE CD_INDICE_2 = 0


UPDATE aux.FINANCIAMENTO_TESTE SET
TX_MULTIPLICADOR_INDICE_2 = REPLACE(TX_MULTIPLICADOR_INDICE_2,',','.')

UPDATE aux.FINANCIAMENTO_TESTE SET
TX_MULTIPLICADOR_INDICE_2 = NULL
WHERE TX_MULTIPLICADOR_INDICE_2 = ' '

ALTER TABLE aux.FINANCIAMENTO_TESTE ALTER COLUMN TX_MULTIPLICADOR_INDICE_2 DECIMAL(20,10)

UPDATE F SET
TX_MULTIPLICADOR_INDICE_2 = 100
FROM aux.FINANCIAMENTO_TESTE F
WHERE CD_INDICE_2 > 0
AND TX_MULTIPLICADOR_INDICE_2 IS NULL



UPDATE aux.FINANCIAMENTO_TESTE SET
TX_ADICIONAL_2 = REPLACE(TX_ADICIONAL_2,',','.')

UPDATE aux.FINANCIAMENTO_TESTE SET
TX_ADICIONAL_2 = NULL
WHERE TX_ADICIONAL_2 = ' '

ALTER TABLE aux.FINANCIAMENTO_TESTE ALTER COLUMN TX_ADICIONAL_2 DECIMAL(20,10)

ALTER TABLE aux.FINANCIAMENTO_TESTE ALTER COLUMN CD_INDICE_FIM INT

UPDATE aux.FINANCIAMENTO_TESTE SET
CD_INDICE_FIM = NULL
WHERE CD_INDICE_FIM = 0


UPDATE aux.FINANCIAMENTO_TESTE SET
TX_MULTIPLICADOR_INDICE_FIM = REPLACE(TX_MULTIPLICADOR_INDICE_FIM,',','.')

UPDATE aux.FINANCIAMENTO_TESTE SET
TX_MULTIPLICADOR_INDICE_FIM = NULL
WHERE TX_MULTIPLICADOR_INDICE_FIM = ' '

ALTER TABLE aux.FINANCIAMENTO_TESTE ALTER COLUMN TX_MULTIPLICADOR_INDICE_FIM DECIMAL(20,10)

UPDATE F SET
TX_MULTIPLICADOR_INDICE_FIM = 100
FROM aux.FINANCIAMENTO_TESTE F
WHERE CD_INDICE_FIM > 0
AND TX_MULTIPLICADOR_INDICE_FIM IS NULL


UPDATE aux.FINANCIAMENTO_TESTE SET
TX_ADICIONAL_FIM = REPLACE(TX_ADICIONAL_FIM,',','.')

UPDATE aux.FINANCIAMENTO_TESTE SET
TX_ADICIONAL_FIM = NULL
WHERE TX_ADICIONAL_FIM = ' '

ALTER TABLE aux.FINANCIAMENTO_TESTE ALTER COLUMN TX_ADICIONAL_FIM DECIMAL(20,10)

ALTER TABLE aux.FINANCIAMENTO_TESTE DROP COLUMN 'COLUNA 13'


SELECT
	ANO,
	SUM(VL_FINANCIAMENTO) AS VL_FINANCIAMENTO
FROM aux.FINANCIAMENTO_TESTE
GROUP BY ANO
ORDER BY ANO

SELECT
	F.CD_EMPRESA,
	SUM(VL_FINANCIAMENTO)/C.VL_CONTA as propor,
	f.ano
FROM aux.FINANCIAMENTO_TESTE F
	INNER JOIN TB_EMPRESA E ON F.CD_EMPRESA = E.CD_EMPRESA
	INNER JOIN TB_CONTA_VALOR C ON E.CD_CVM = C.CD_CVM AND F.ANO = C.ANO
WHERE 
	CD_CONTA_P1 = 1
	AND CD_CONTA_P2 IS NULL
	AND CD_CONTA_P3 IS NULL
	AND CD_CONTA_P4 IS NULL
	AND CD_CONTA_P5 IS NULL
GROUP BY F.CD_EMPRESA, C.VL_CONTA, F.ANO
ORDER BY propor desc

30.499.395

SELECT *
FROM TB_CONTA_VALOR
where CD_CVM = 20257
and ANO = 2013

select *
from dbo.TB_EMPRESA

select *
from aux.FINANCIAMENTO_TESTE