SELECT *
FROM aux.EMPRESAS_ECONOMATICA A
	INNER JOIN aux.EMPRESAS_ECONOMATICA_2 B ON A.Código = B.Código

UPDATE aux.EMPRESAS_ECONOMATICA SET
Código = 'COGN3'
WHERE Código = 'KROT3'

SELECT *
FROM aux.EMPRESAS_ECONOMATICA_2
WHERE NOME LIKE '%KROTON%'

SELECT *
FROM aux.EMPRESAS_ECONOMATICA

SELECT *
FROM aux.EMPRESAS_CVM

SELECT TOP 100 *
FROM TB_CONTA_VALOR