CREATE TABLE dbo.FINAL (
CD_FINAL INT PRIMARY KEY IDENTITY(1,1),
CD_EMPRESA INT,
ANO INT,
XD DECIMAL(20,10),
KD DECIMAL(20,10),
XE DECIMAL(20,10),
KE DECIMAL(20,10),
WACC DECIMAL(20,10),
NOPAT DECIMAL(30,10),
INVESTED_CAPITAL DECIMAL(30,10),
ROIC DECIMAL(20,10),
EVA DECIMAL(30,10),
LL DECIMAL(30,10),
PASSIVO DECIMAL(30,10),
PL DECIMAL(30,10),
)

CREATE TABLE dbo.TB_BETA (
	CD_BETA INT PRIMARY KEY IDENTITY(1,1),
	CD_CVM INT,
	ANO INT,
	TX_BETA DECIMAL(19,10)
)

CREATE TABLE dbo.TB_EMPRESA (
	CD_EMPRESA INT PRIMARY KEY,
	CD_CVM INT,
	CNPJ VARCHAR(20),
	NOME VARCHAR(100),
	CD_SETOR INT,
	CD_SEGMENTO INT
)


CREATE TABLE dbo.TB_FINANCIAMENTO (
	CD_FINANCIAMENTO INT PRIMARY KEY IDENTITY(1,1),
	CD_EMPRESA INT,
	ANO INT,
	DS_FINANCIAMENTO VARCHAR(200),
	CD_INDICE INT,
	TX_MULTIPLICADOR_INDICE DECIMAL(20,10),
	TX_ADICIONAL DECIMAL(20,10),
	CD_INDICE_2 INT,
	TX_MULTIPLICADOR_INDICE_2 DECIMAL(20,10),
	TX_ADICIONAL_2 DECIMAL(20,10),
	CD_INDICE_FIM INT,
	TX_MULTIPLICADOR_INDICE_FIM DECIMAL(20,10),
	TX_ADICIONAL_FIM DECIMAL(20,10)
)


CREATE TABLE dbo.TB_INDICE (
	CD_INDICE INT PRIMARY KEY,
	NM_INDICE VARCHAR(100)
)


CREATE TABLE dbo.TB_INDICE_ANO (
	CD_INDICE_ANO INT PRIMARY KEY IDENTITY(1,1),
	CD_INDICE INT,
	ANO INT,
	TX_INDICE DECIMAL(19,10)
)

CREATE TABLE TB_SETOR (
	CD_SETOR INT,
	NM_SETOR VARCHAR(100)
)


CREATE TABLE TB_BETA_SETOR (
	CD_BETA_SETOR INT PRIMARY KEY IDENTITY(1,1),
	ANO INT,
	CD_SETOR INT,
	BETA DECIMAL(20,10)
)

CREATE TABLE TB_BETA_ALAVANCADO (
	CD_BETA_ALAVANCADO INT PRIMARY KEY IDENTITY(1,1),
	ANO INT,
	CD_EMPRESA INT,
	BETA DECIMAL(20,10)
)