
CREATE TABLE dbo.TB_BETA (
	CD_BETA INT PRIMARY KEY IDENTITY(1,1),
	CD_CVM INT,
	ANO INT,
	TX_BETA DECIMAL(19,10)
)

CREATE TABLE dbo.TB_EMPRESA (
	CD_EMPRESA INT PRIMARY KEY,
	CD_CVM INT,
	CNPJ VARCHAR(20),
	NOME VARCHAR(100),
	CD_SETOR INT,
	CD_SEGMENTO INT
)


CREATE TABLE dbo.TB_FINANCIAMENTO (
	CD_FINANCIAMENTO INT PRIMARY KEY IDENTITY(1,1),
	CD_EMPRESA INT,
	ANO INT,
	DS_FINANCIAMENTO VARCHAR(200),
	CD_INDICE INT,
	TX_MULTIPLICADOR_INDICE DECIMAL(20,10),
	TX_ADICIONAL DECIMAL(20,10),
	CD_INDICE_2 INT,
	TX_MULTIPLICADOR_INDICE_2 DECIMAL(20,10),
	TX_ADICIONAL_2 DECIMAL(20,10),
	CD_INDICE_FIM INT,
	TX_MULTIPLICADOR_INDICE_FIM DECIMAL(20,10),
	TX_ADICIONAL_FIM DECIMAL(20,10)
)


CREATE TABLE dbo.TB_INDICE (
	CD_INDICE INT PRIMARY KEY,
	NM_INDICE VARCHAR(100)
)


CREATE TABLE dbo.TB_INDICE_ANO (
	CD_INDICE_ANO INT PRIMARY KEY IDENTITY(1,1),
	CD_INDICE INT,
	ANO INT,
	TX_INDICE DECIMAL(19,10)
)