DROP TABLE IF EXISTS FINAL

CREATE TABLE dbo.FINAL (
CD_FINAL INT PRIMARY KEY IDENTITY(1,1),
CD_EMPRESA INT,
ANO INT,
XD DECIMAL(20,10),
KD DECIMAL(20,10),
XE DECIMAL(20,10),
KE DECIMAL(20,10),
WACC DECIMAL(20,10),
NOPAT DECIMAL(30,10),
INVESTED_CAPITAL DECIMAL(30,10),
ROIC DECIMAL(20,10),
EVA DECIMAL(30,10),
LL DECIMAL(30,10),
PASSIVO DECIMAL(30,10),
PL DECIMAL(30,10),
)


-- Traz dados iniciais

INSERT INTO FINAL (CD_EMPRESA, ANO)
SELECT DISTINCT CD_EMPRESA, ANO
FROM TB_FINANCIAMENTO

-- Exclui SABESP (nao tem dados de nenhum ano) e RaiaDrograsil (nao tem dados de 2013 e 2014)

DELETE FROM FINAL WHERE CD_EMPRESA IN (11,17)

-- Traz Lucro Liquido

UPDATE F SET
F.LL = C.VL_CONTA
FROM FINAL F
	INNER JOIN TB_EMPRESA E ON F.CD_EMPRESA = E.CD_EMPRESA
	INNER JOIN TB_CONTA_VALOR C ON F.ANO = C.ANO AND E.CD_CVM = C.CD_CVM
WHERE CD_CONTA_P1 = 3
	AND CD_CONTA_P2 = 11
	AND CD_CONTA_P3 IS NULL

---- Traz o Passivo

--UPDATE F SET
--F.PASSIVO =	C.SOMA	
--FROM FINAL F
--	INNER JOIN TB_EMPRESA E ON F.CD_EMPRESA = E.CD_EMPRESA
--	INNER JOIN (SELECT SUM(VL_CONTA) AS SOMA, ANO, CD_CVM FROM TB_CONTA_VALOR 
--											WHERE CD_CONTA_P1 = 2
--												AND CD_CONTA_P2 IN (1,2)
--												AND CD_CONTA_P3 IS NULL
--											GROUP BY ANO, CD_CVM)
--												AS C ON F.ANO = C.ANO AND E.CD_CVM = C.CD_CVM

-- Traz o Passivo Oneroso

UPDATE F SET
F.PASSIVO =	FI.VL_FINANCIAMENTO_ANO	
FROM FINAL F
	INNER JOIN TB_FINANCIAMENTO FI ON F.CD_EMPRESA = FI.CD_EMPRESA AND F.ANO = FI.ANO


-- Traz PL

UPDATE F SET
F.PL = C.VL_CONTA
FROM FINAL F
	INNER JOIN TB_EMPRESA E ON F.CD_EMPRESA = E.CD_EMPRESA
	INNER JOIN TB_CONTA_VALOR C ON F.ANO = C.ANO AND E.CD_CVM = C.CD_CVM
WHERE CD_CONTA_P1 = 2
	AND CD_CONTA_P2 = 3
	AND CD_CONTA_P3 IS NULL

-- Traz o XD e o XE

UPDATE F SET
XD = PASSIVO / ( PASSIVO + PL ),
XE = PL / ( PASSIVO + PL )
FROM FINAL F

-- Ajustar XD e XE negativos

UPDATE F SET
XD = 1,
XE = 0
FROM FINAL F
WHERE PL <= 0