-- Eliminar indices de cambio

UPDATE dbo.TB_FINANCIAMENTO SET
	CD_INDICE = NULL,
	TX_MULTIPLICADOR_INDICE = NULL
WHERE CD_INDICE IN (11,38)

UPDATE dbo.TB_FINANCIAMENTO SET
	CD_INDICE_2 = NULL,
	TX_MULTIPLICADOR_INDICE_2 = NULL
WHERE CD_INDICE_2 IN (11,38)

UPDATE dbo.TB_FINANCIAMENTO SET
	CD_INDICE_FIM = NULL,
	TX_MULTIPLICADOR_INDICE_FIM = NULL
WHERE CD_INDICE_FIM IN (11,38)

-- Ajustar LIBOR para LIBOR 3M

UPDATE dbo.TB_FINANCIAMENTO SET
	CD_INDICE = 3
WHERE CD_INDICE = 24

UPDATE dbo.TB_FINANCIAMENTO SET
	CD_INDICE_2 = 3
WHERE CD_INDICE_2 = 24

UPDATE dbo.TB_FINANCIAMENTO SET
	CD_INDICE_FIM = 3
WHERE CD_INDICE_FIM = 24

-- Adicionar total de financimentos por ano

ALTER TABLE TB_FINANCIAMENTO ADD VL_FINANCIAMENTO_ANO BIGINT

WITH FINANCIAMENTO_ANO AS (
SELECT 
	CD_EMPRESA,
	ANO,
	SUM(VL_FINANCIAMENTO) AS VL_FINANCIAMENTO_ANO
FROM TB_FINANCIAMENTO
GROUP BY
	CD_EMPRESA,
	ANO
	)
UPDATE F SET
F.VL_FINANCIAMENTO_ANO = FA.VL_FINANCIAMENTO_ANO
FROM TB_FINANCIAMENTO F
	INNER JOIN FINANCIAMENTO_ANO FA ON F.CD_EMPRESA = FA.CD_EMPRESA AND F.ANO = FA.ANO

-- Adicionar percentuais do financiamento

ALTER TABLE TB_FINANCIAMENTO ADD PCT_FINANCIAMENTO DECIMAL(20,10)

UPDATE TB_FINANCIAMENTO SET
PCT_FINANCIAMENTO = CAST(VL_FINANCIAMENTO AS DECIMAL(20,10)) / CAST(VL_FINANCIAMENTO_ANO AS DECIMAL(20,10))

-- Calcular KD do financiamento

ALTER TABLE TB_FINANCIAMENTO ADD KD_1 DECIMAL(20,10)
ALTER TABLE TB_FINANCIAMENTO ADD KD_2 DECIMAL(20,10)
ALTER TABLE TB_FINANCIAMENTO ADD KD_FIM DECIMAL(20,10)
ALTER TABLE TB_FINANCIAMENTO ADD KD_FINANCIAMENTO DECIMAL(20,10)
ALTER TABLE TB_FINANCIAMENTO ADD KD_PROPORCIONAL DECIMAL(20,10)

UPDATE F SET
F.KD_1 = CASE 
			WHEN F.CD_INDICE IS NULL 
			THEN F.TX_ADICIONAL
			ELSE (IA.TX_INDICE * F.TX_MULTIPLICADOR_INDICE / 100) + ISNULL(F.TX_ADICIONAL,0)
		END
FROM TB_FINANCIAMENTO F
	LEFT JOIN TB_INDICE_ANO IA ON F.CD_INDICE = IA.CD_INDICE AND F.ANO = IA.ANO

UPDATE F SET
F.KD_2 = CASE 
			WHEN F.CD_INDICE_2 IS NULL 
			THEN F.TX_ADICIONAL_2
			ELSE (IA.TX_INDICE * F.TX_MULTIPLICADOR_INDICE_2 / 100) + ISNULL(F.TX_ADICIONAL_2,0)
		END
FROM TB_FINANCIAMENTO F
	LEFT JOIN TB_INDICE_ANO IA ON F.CD_INDICE_2 = IA.CD_INDICE AND F.ANO = IA.ANO

UPDATE F SET
F.KD_FIM = CASE 
			WHEN F.CD_INDICE_FIM IS NULL 
			THEN F.TX_ADICIONAL_FIM
			ELSE (IA.TX_INDICE * F.TX_MULTIPLICADOR_INDICE_FIM / 100) + ISNULL(F.TX_ADICIONAL_FIM,0)
		END
FROM TB_FINANCIAMENTO F
	LEFT JOIN TB_INDICE_ANO IA ON F.CD_INDICE_FIM = IA.CD_INDICE AND F.ANO = IA.ANO

UPDATE F SET
F.KD_FINANCIAMENTO = CASE 
						WHEN KD_FIM IS NULL 
						THEN ISNULL(KD_1,0) + ISNULL(KD_2,0)
						ELSE ( ISNULL(KD_1,0) + ISNULL(KD_2,0) + KD_FIM ) / 2
					END
FROM TB_FINANCIAMENTO F

UPDATE F SET
F.KD_PROPORCIONAL = KD_FINANCIAMENTO * PCT_FINANCIAMENTO
FROM TB_FINANCIAMENTO F

-- Atualizar KD na tabela FINAL

WITH KD_SOMA AS (
	SELECT 
		CD_EMPRESA,
		ANO,
		SUM(KD_PROPORCIONAL) AS KD
	FROM TB_FINANCIAMENTO
	GROUP BY 
		CD_EMPRESA,
		ANO
)
UPDATE F SET
F.KD = K.KD
FROM FINAL F
	INNER JOIN KD_SOMA K ON F.CD_EMPRESA = K.CD_EMPRESA AND F.ANO = K.ANO

