-- Inserir dados iniciais

INSERT INTO TB_BETA_ALAVANCADO (ANO, CD_EMPRESA)
SELECT 
	ANO,
	CD_EMPRESA
FROM FINAL

-- Calcular beta
;
WITH TB_PASSIVO AS (
	SELECT
		CD_EMPRESA,	
		BS.ANO,
		C.SOMA AS PASSIVO
	FROM TB_EMPRESA E
		INNER JOIN TB_BETA_SETOR BS ON E.CD_SETOR = BS.CD_SETOR
		INNER JOIN (SELECT SUM(VL_CONTA) AS SOMA, ANO, CD_CVM FROM TB_CONTA_VALOR 
												WHERE CD_CONTA_P1 = 2
													AND CD_CONTA_P2 IN (1,2)
													AND CD_CONTA_P3 IS NULL
												GROUP BY ANO, CD_CVM)
													AS C ON BS.ANO = C.ANO AND E.CD_CVM = C.CD_CVM
),
TB_PL AS (
	SELECT
		CD_EMPRESA,
		BS.ANO,
		C.VL_CONTA AS PL
	FROM TB_EMPRESA E
		INNER JOIN TB_BETA_SETOR BS ON E.CD_SETOR = BS.CD_SETOR
		INNER JOIN TB_CONTA_VALOR C ON BS.ANO = C.ANO AND E.CD_CVM = C.CD_CVM
	WHERE CD_CONTA_P1 = 2
		AND CD_CONTA_P2 = 3
		AND CD_CONTA_P3 IS NULL
)
UPDATE BA SET
BA.BETA = BS.BETA * ( 1 + (1 - 0.34) * ( PA.PASSIVO / PL.PL ) )
FROM TB_BETA_ALAVANCADO BA
	INNER JOIN TB_PASSIVO PA ON BA.ANO = PA.ANO AND BA.CD_EMPRESA = PA.CD_EMPRESA
	INNER JOIN TB_PL PL ON BA.ANO = PL.ANO AND BA.CD_EMPRESA = PL.CD_EMPRESA
	INNER JOIN TB_EMPRESA E ON BA.CD_EMPRESA = E.CD_EMPRESA
	INNER JOIN TB_BETA_SETOR BS ON E.CD_SETOR = BS.CD_SETOR