-- Calcular KE

;WITH RF_US AS (
SELECT
	ANO,
	TX_INDICE
FROM TB_INDICE_ANO
WHERE CD_INDICE = 39
),
RF_BR AS (
SELECT
	ANO,
	TX_INDICE
FROM TB_INDICE_ANO
WHERE CD_INDICE = 2
),
PREMIO AS (
SELECT
	ANO,
	TX_INDICE
FROM TB_INDICE_ANO
WHERE CD_INDICE = 40
)
UPDATE F SET
F.KE = US.TX_INDICE + ( B.BETA * P.TX_INDICE ) + BR.TX_INDICE - US.TX_INDICE 
FROM FINAL F
	INNER JOIN RF_US US ON F.ANO = US.ANO
	INNER JOIN TB_BETA_ALAVANCADO B ON F.CD_EMPRESA = B.CD_EMPRESA AND F.ANO = B.ANO
	INNER JOIN PREMIO P ON F.ANO = P.ANO
	INNER JOIN RF_BR BR ON F.ANO = BR.ANO

-- Calcular WACC

UPDATE FINAL SET
WACC = (( KE * XE ) + ( KD * XD * ( 1 - 0.34 ) )) / 100

-- Calcular EVA

UPDATE FINAL SET
EVA = ( ROIC  - WACC ) * INVESTED_CAPITAL