-- Adicionar colunas 

ALTER TABLE FINAL ADD SPREAD DECIMAL(20,10)
ALTER TABLE FINAL ADD VAR_EVA DECIMAL(20,10)
ALTER TABLE FINAL ADD VAR_EVA_PCT DECIMAL(20,10)

-- Calcular spread

UPDATE FINAL SET
SPREAD = ROIC - WACC

-- Calcular variacao do EVA

UPDATE F SET
F.VAR_EVA = NULL
FROM FINAL F

;WITH BASE AS (
SELECT *
FROM FINAL
)
UPDATE F SET
F.VAR_EVA = F.EVA - B.EVA
FROM FINAL F
	INNER JOIN BASE B ON F.CD_EMPRESA = B.CD_EMPRESA AND F.ANO - 1 = B.ANO

UPDATE F SET
F.VAR_EVA_PCT = NULL
FROM FINAL F

;WITH BASE AS (
SELECT *
FROM FINAL
)
UPDATE F SET
F.VAR_EVA_PCT = ( F.EVA - B.EVA ) / ABS(B.EVA)
FROM FINAL F
	INNER JOIN BASE B ON F.CD_EMPRESA = B.CD_EMPRESA AND F.ANO - 1 = B.ANO

-- Gerar relatorio final

SELECT  
	E.NOME,
	CASE WHEN EE.NOME IS NOT NULL THEN EE.[Subsetor Bovespa] ELSE 'Diversos' END AS SUBSETOR,
	ANO,
	XD,
	KD / 100 AS KD,
	XE,
	KE / 100 AS KE,
	NOPAT,
	INVESTED_CAPITAL,
	PASSIVO AS PASSIVO_ONEROSO,
	PL,
	WACC,
	ROIC,
	SPREAD,
	EVA,
	LL,
	VAR_EVA,
	VAR_EVA_PCT
FROM FINAL F 
	INNER JOIN TB_EMPRESA E ON F.CD_EMPRESA = E.CD_EMPRESA
	LEFT JOIN aux.EMPRESAS_ECONOMATICA_3 EE ON E.NOME = EE.NOME
--	WHERE EVA > 0
ORDER BY E.NOME, ANO