UPDATE aux.EMPRESAS_ECONOMATICA_2 SET
BETA_2013 = REPLACE(BETA_2013,',','.')

UPDATE aux.EMPRESAS_ECONOMATICA_2 SET
BETA_2014 = REPLACE(BETA_2014,',','.')

UPDATE aux.EMPRESAS_ECONOMATICA_2 SET
BETA_2015 = REPLACE(BETA_2015,',','.')

UPDATE aux.EMPRESAS_ECONOMATICA_2 SET
BETA_2016 = REPLACE(BETA_2016,',','.')

UPDATE aux.EMPRESAS_ECONOMATICA_2 SET
BETA_2017 = REPLACE(BETA_2017,',','.')

UPDATE aux.EMPRESAS_ECONOMATICA_2 SET
BETA_2018 = REPLACE(BETA_2018,',','.')

INSERT INTO dbo.TB_BETA (CD_CVM, ANO, TX_BETA)
SELECT
	A.CD_CVM,
	2013,
	B.BETA_2013
FROM aux.EMPRESAS_ECONOMATICA A
	INNER JOIN aux.EMPRESAS_ECONOMATICA_2 B ON A.Código = B.Código

INSERT INTO dbo.TB_BETA (CD_CVM, ANO, TX_BETA)
SELECT
	A.CD_CVM,
	2014,
	B.BETA_2014
FROM aux.EMPRESAS_ECONOMATICA A
	INNER JOIN aux.EMPRESAS_ECONOMATICA_2 B ON A.Código = B.Código

INSERT INTO dbo.TB_BETA (CD_CVM, ANO, TX_BETA)
SELECT
	A.CD_CVM,
	2015,
	B.BETA_2015
FROM aux.EMPRESAS_ECONOMATICA A
	INNER JOIN aux.EMPRESAS_ECONOMATICA_2 B ON A.Código = B.Código

INSERT INTO dbo.TB_BETA (CD_CVM, ANO, TX_BETA)
SELECT
	A.CD_CVM,
	2016,
	B.BETA_2016
FROM aux.EMPRESAS_ECONOMATICA A
	INNER JOIN aux.EMPRESAS_ECONOMATICA_2 B ON A.Código = B.Código

INSERT INTO dbo.TB_BETA (CD_CVM, ANO, TX_BETA)
SELECT
	A.CD_CVM,
	2017,
	B.BETA_2017
FROM aux.EMPRESAS_ECONOMATICA A
	INNER JOIN aux.EMPRESAS_ECONOMATICA_2 B ON A.Código = B.Código

INSERT INTO dbo.TB_BETA (CD_CVM, ANO, TX_BETA)
SELECT
	A.CD_CVM,
	2018,
	B.BETA_2018
FROM aux.EMPRESAS_ECONOMATICA A
	INNER JOIN aux.EMPRESAS_ECONOMATICA_2 B ON A.Código = B.Código

	SELECT *
	FROM TB_BETA
