WITH TB_NOPAT AS (
SELECT 
	CD_CVM,
	ANO,
	VL_CONTA,
	VL_CONTA * (1 - 0.34) AS NOPAT
FROM TB_CONTA_VALOR
WHERE CD_CONTA_P1 = 3
AND CD_CONTA_P2 = 5
)
UPDATE F SET
F.NOPAT = N.NOPAT
FROM FINAL F
	INNER JOIN TB_EMPRESA E ON F.CD_EMPRESA = E.CD_EMPRESA
	INNER JOIN TB_NOPAT N ON F.ANO = N.ANO AND E.CD_CVM = N.CD_CVM