-- Ajustes nas tabelas

ALTER TABLE aux.EMPRESAS_CVM ALTER COLUMN CNPJ_CIA BIGINT
ALTER TABLE AUX.EMPRESAS_ECONOMATICA ALTER COLUMN CNPJ VARCHAR(18)
ALTER TABLE AUX.EMPRESAS_CVM ALTER COLUMN CNPJ_CIA VARCHAR(18)
ALTER TABLE AUX.EMPRESAS_ECONOMATICA ADD CNPJ VARCHAR(50)
ALTER TABLE AUX.EMPRESAS_ECONOMATICA ADD ID INT IDENTITY(1,1)

-- Pesquisar empresas do TCC

SELECT ID AS CD_EMPRESA,
	NOME,
	CNPJ
FROM AUX.EMPRESAS_ECONOMATICA

-- Pesquisar empresas pelo nome para pegar CNPJ

SELECT *
FROM aux.empresas_cvm
WHERE DENOM_SOCIAL LIKE '%Localiza%'
AND SIT = 'ATIVO'

-- Atualizar CNPJ

UPDATE AUX.EMPRESAS_ECONOMATICA SET
CNPJ = '16.670.085/0001-55'
WHERE ID = 6