-- Ajustes nas tabelas

ALTER TABLE aux.EMPRESAS_CVM ALTER COLUMN CNPJ_CIA BIGINT
ALTER TABLE AUX.EMPRESAS_ECONOMATICA ALTER COLUMN CNPJ VARCHAR(18)
ALTER TABLE AUX.EMPRESAS_CVM ALTER COLUMN CNPJ_CIA VARCHAR(18)
ALTER TABLE AUX.EMPRESAS_ECONOMATICA ADD CNPJ VARCHAR(50)
ALTER TABLE AUX.EMPRESAS_ECONOMATICA ADD ID INT IDENTITY(1,1)

-- Pesquisar empresas do TCC

SELECT ID AS CD_EMPRESA,
	NOME,
	CNPJ
SELECT *
FROM AUX.EMPRESAS_ECONOMATICA

-- Pesquisar empresas pelo nome para pegar CNPJ

SELECT VL_CONTA,C.*
SELECT *
FROM aux.empresas_cvm C
	--INNER JOIN DBO.TB_CONTA_VALOR V ON C.CD_CVM = V.CD_CVM
WHERE DENOM_COMERC LIKE '%DROGASIL%'
AND SIT = 'ATIVO'
--AND ANO = 2013
--AND CD_CONTA_P1 = 1
--AND CD_CONTA_P2 IS NULL

-- Atualizar CNPJ

UPDATE AUX.EMPRESAS_ECONOMATICA SET
CNPJ = '16.670.085/0001-55'
WHERE ID = 6

SELECT *
FROM DB_EVA.aux.EMPRESAS_CVM
WHERE denom_social LIKE '%Ecorodovias%'