SELECT *
FROM DB_EVA.AUX.EMPRESAS_CVM

SELECT *
FROM DB_EVA.AUX.EMPRESAS_ECONOMATICA

SELECT*
FROM DB_EVA.AUX.DRE_CIA_ABERTA_CON_2014

SELECT*
FROM DB_EVA.AUX.BPP_CIA_ABERTA_CON_2014


SELECT *
FROM DB_EVA.AUX.BPA_CIA_ABERTA_CON_2014

SELECT
SUBSTRING(CD_CONTA,0,CHARINDEX('.',CD_CONTA,0))
FROM DB_EVA.AUX.BPA_CIA_ABERTA_CON_2014

SELECT
SUBSTRING(CD_CONTA,CHARINDEX('.',CD_CONTA)+1,LEN(CD_CONTA))
SELECT CHARINDEX('.',CD_CONTA)+1
FROM DB_EVA.AUX.BPA_CIA_ABERTA_CON_2014

SELECT *,
	1 AS CD_DEMONSTRACAO,
	2014 AS ANO
INTO dbo.TB_CONTA_VALOR
FROM DB_EVA.AUX.BPA_CIA_ABERTA_CON_2014

SELECT *
FROM dbo.TB_CONTA_VALOR




INSERT INTO dbo.TB_CONTA_VALOR
SELECT *,
	1 AS CD_DEMONSTRACAO,
	2018 AS ANO
FROM DB_EVA.AUX.BPA_CIA_ABERTA_CON_2018

INSERT INTO dbo.TB_CONTA_VALOR
SELECT *,
	2 AS CD_DEMONSTRACAO,
	2018 AS ANO
FROM DB_EVA.AUX.BPP_CIA_ABERTA_CON_2018

ALTER TABLE dbo.TB_CONTA_VALOR ALTER COLUMN CD_DEMONSTRACAO INT
ALTER TABLE dbo.TB_CONTA_VALOR ALTER COLUMN ANO INT



INSERT INTO dbo.TB_CONTA_VALOR
SELECT 
	CNPJ_CIA
	,DT_REFER
	,VERSAO
	,DENOM_CIA
	,CD_CVM
	,GRUPO_DFP
	,MOEDA
	,ESCALA_MOEDA
	,ORDEM_EXERC
	,DT_FIM_EXERC
	,CD_CONTA
	,DS_CONTA
	,VL_CONTA,
	3 AS CD_DEMONSTRACAO,
	2018 AS ANO
FROM DB_EVA.AUX.DRE_CIA_ABERTA_CON_2018

SELECT TOP 1000 *
FROM dbo.TB_CONTA_VALOR

ALTER TABLE dbo.TB_CONTA_VALOR ALTER COLUMN VL_CONTA DECIMAL(38,2)

ALTER TABLE dbo.TB_CONTA_VALOR ADD CD_CONTA_A INT

UPDATE dbo.TB_CONTA_VALOR SET
CD_CONTA_A = SUBSTRING(CD_CONTA,3,2)

ALTER TABLE dbo.TB_CONTA_VALOR ADD CD_CONTA_B INT

UPDATE dbo.TB_CONTA_VALOR SET
CD_CONTA_B = SUBSTRING(CD_CONTA,6,2)

ALTER TABLE dbo.TB_CONTA_VALOR ADD CD_CONTA_B INT

UPDATE dbo.TB_CONTA_VALOR SET
CD_CONTA_B = SUBSTRING(CD_CONTA,6,2)

ALTER TABLE dbo.TB_CONTA_VALOR DROP COLUMN CD_CONTA_A

SELECT TOP 1000 *
FROM dbo.TB_CONTA_VALOR

EXEC sp_RENAME 'dbo.TB_CONTA_VALOR.CD_CONTA' , 'CD_CONTA_VARCHAR', 'COLUMN'

ALTER TABLE dbo.TB_CONTA_VALOR ADD CD_CONTA INT

UPDATE dbo.TB_CONTA_VALOR SET
CD_CONTA = CONCAT( 
	SUBSTRING(CD_CONTA_VARCHAR,1,1),
	SUBSTRING(CD_CONTA_VARCHAR,3,2),
	SUBSTRING(CD_CONTA_VARCHAR,6,2),
	SUBSTRING(CD_CONTA_VARCHAR,9,2),
	SUBSTRING(CD_CONTA_VARCHAR,12,2)
	)

SELECT TOP 100 *
FROM dbo.TB_CONTA_VALOR

ALTER TABLE dbo.TB_CONTA_VALOR DROP COLUMN CD_CONTA

ALTER TABLE dbo.TB_CONTA_VALOR ADD CD_CONTA_P1 INT
ALTER TABLE dbo.TB_CONTA_VALOR ADD CD_CONTA_P2 INT
ALTER TABLE dbo.TB_CONTA_VALOR ADD CD_CONTA_P3 INT
ALTER TABLE dbo.TB_CONTA_VALOR ADD CD_CONTA_P4 INT
ALTER TABLE dbo.TB_CONTA_VALOR ADD CD_CONTA_P5 INT

UPDATE dbo.TB_CONTA_VALOR SET
CD_CONTA_P1 = SUBSTRING(CD_CONTA_VARCHAR,1,1)

UPDATE dbo.TB_CONTA_VALOR SET
CD_CONTA_P2 = SUBSTRING(CD_CONTA_VARCHAR,3,2)

UPDATE dbo.TB_CONTA_VALOR SET
CD_CONTA_P3 = SUBSTRING(CD_CONTA_VARCHAR,6,2)

UPDATE dbo.TB_CONTA_VALOR SET
CD_CONTA_P4 = SUBSTRING(CD_CONTA_VARCHAR,9,2)

UPDATE dbo.TB_CONTA_VALOR SET
CD_CONTA_P5 = SUBSTRING(CD_CONTA_VARCHAR,12,2)

UPDATE dbo.TB_CONTA_VALOR SET
CD_CONTA_P1 = NULL
WHERE CD_CONTA_P1 = ''

UPDATE dbo.TB_CONTA_VALOR SET
CD_CONTA_P2 = NULL
WHERE CD_CONTA_P2 = ''

UPDATE dbo.TB_CONTA_VALOR SET
CD_CONTA_P3 = NULL
WHERE CD_CONTA_P3 = ''

UPDATE dbo.TB_CONTA_VALOR SET
CD_CONTA_P4 = NULL
WHERE CD_CONTA_P4 = ''

UPDATE dbo.TB_CONTA_VALOR SET
CD_CONTA_P5 = NULL
WHERE CD_CONTA_P5 = ''

SELECT 
	DISTINCT DS_CONTA,
	CD_CONTA_P1,
	CD_CONTA_P2,
	CD_CONTA_P3,
	CD_CONTA_P4,
	CD_CONTA_P5
FROM dbo.TB_CONTA_VALOR 
ORDER BY
	CD_CONTA_P1,
	CD_CONTA_P2,
	CD_CONTA_P3,
	CD_CONTA_P4,
	CD_CONTA_P5


SELECT *
FROM dbo.TB_CONTA_VALOR 
WHERE
	CD_CONTA_P1 = 3
	AND CD_CONTA_P2 = 1
	AND CD_CONTA_P3 IS NULL

SELECT DISTINCT C.CD_CVM,
	E.DENOM_COMERC
FROM dbo.TB_CONTA_VALOR C
	INNER JOIN AUX.EMPRESAS_CVM E ON C.CD_CVM = E.CD_CVM
ORDER BY E.DENOM_COMERC

--SELECT
--CONCAT( 
--	SUBSTRING(CD_CONTA,1,1),
--	SUBSTRING(CD_CONTA,3,2),
--	SUBSTRING(CD_CONTA,6,2),
--	SUBSTRING(CD_CONTA,9,2),
--	SUBSTRING(CD_CONTA,12,2)
--	)
--FROM DB_EVA.AUX.BPA_CIA_ABERTA_CON_2014
--SELECT TOP 10 * FROM DB_EVA.AUX.BPA_CIA_ABERTA_CON_2014


SELECT *
FROM AUX.EMPRESAS_CVM

SELECT *
FROM aux.EMPRESAS_ECONOMATICA


UPDATE dbo.TB_CONTA_VALOR SET
ORDEM_EXERC = NULL
WHERE ORDEM_EXERC = 'PENÚLTIMO'
	AND DT_FIM_EXERC = '2013-12-31'

DELETE FROM dbo.TB_CONTA_VALOR
WHERE ORDEM_EXERC = 'PENÚLTIMO'

ALTER TABLE dbo.TB_CONTA_VALOR DROP COLUMN ORDEM_EXERC

SELECT MAX(VL_CONTA) VL_CONTA, DENOM_CIA
FROM dbo.TB_CONTA_VALOR
WHERE ANO = 2018
	AND CD_CONTA_P1 = 3
	AND CD_CONTA_P2 = 1
	AND CD_CONTA_P3 IS NULL
	GROUP BY DENOM_CIA
	ORDER BY VL_CONTA DESC

ALTER TABLE aux.EMPRESAS_ECONOMATICA ADD CD_CVM INT


UPDATE E SET
E.CD_CVM = C.CD_CVM
FROM aux.EMPRESAS_ECONOMATICA E
	INNER JOIN aux.EMPRESAS_CVM C ON E.CNPJ = C.CNPJ_CIA

UPDATE AUX.EMPRESAS_ECONOMATICA SET
CD_CVM = 3980
WHERE ID = 24

SELECT ID, Nome, CD_CVM
FROM aux.EMPRESAS_ECONOMATICA
where cd_cvm = 8656
WHERE CD_CVM IS NULL

select cd_cvm,
	COUNT(1)
FROM aux.EMPRESAS_ECONOMATICA
group by cd_cvm
having COUNT(1) > 1

CREATE TABLE dbo.TB_PLANO_CONTAS (
	CD_PLANO_CONTAS INT PRIMARY KEY IDENTITY(1,1),
	DS_CONTA VARCHAR(200),
	CD_CONTA_P1 INT,
	CD_CONTA_P2 INT,
	CD_CONTA_P3 INT,
	CD_CONTA_P4 INT,
	CD_CONTA_P5 INT
)


INSERT INTO dbo.TB_PLANO_CONTAS
SELECT 
	DISTINCT DS_CONTA,
	CD_CONTA_P1,
	CD_CONTA_P2,
	CD_CONTA_P3,
	CD_CONTA_P4,
	CD_CONTA_P5
FROM dbo.TB_CONTA_VALOR V
	INNER JOIN aux.EMPRESAS_ECONOMATICA E ON V.CD_CVM = E.CD_CVM
ORDER BY
	CD_CONTA_P1,
	CD_CONTA_P2,
	CD_CONTA_P3,
	CD_CONTA_P4,
	CD_CONTA_P5

SELECT *
FROM TB_PLANO_CONTAS

DELETE V
FROM dbo.TB_CONTA_VALOR V
	LEFT JOIN aux.EMPRESAS_ECONOMATICA E ON V.CD_CVM = E.CD_CVM
WHERE NOME IS NULL



UPDATE dbo.TB_CONTA_VALOR SET
ANO = 2013
WHERE LEFT(DT_FIM_EXERC,4) = '2013' 

SELECT *
FROM dbo.TB_CONTA_VALOR V
WHERE CD_CONTA_P1 = 1
	AND CD_CONTA_P2 IS NULL
ORDER BY VL_CONTA DESC

SELECT CD_CVM, COUNT(1)
FROM dbo.TB_CONTA_VALOR V
WHERE CD_CONTA_P1 = 1
	AND CD_CONTA_P2 IS NULL
GROUP BY CD_CVM
HAVING COUNT(1) < 6

SELECT *
FROM dbo.TB_CONTA_VALOR V
WHERE CD_CONTA_P1 = 1
	AND CD_CONTA_P2 IS NULL
	AND CD_CVM = 5258


SELECT *
FROM dbo.TB_CONTA_VALOR V